## Foodies Shop Ranker

---

The code logic is hidden in foodies/shop_ranker.py (ShopRanker) class

Here the class `ShopRanker` would accept shop dataframe, weight of scoring,and distance_scorer

Then we can call `get_top_rank` function to get the top N shop which obtained the highest score based on our logic.

In [9]:
from foodies.shop_ranker import ShopRanker
import pandas as pd

In [10]:
shop = pd.read_csv("./data/preped_shop").drop(['Unnamed: 0','scores_breakdown','scores'], axis = 1)

first_weight =  {
     'tel_count': 0.3,
     'has_website': 0.8,
     'has_line': 0.6,
     'has_facebook':0.4,
     'has_instagram': 0.7,
     'has_all': 0.3,
     'has_carpark_i':0.9,
     'open_period_count': 0.2,
     'shop_average_log_price': -0.75,
     'near_shop_counts_log': 0.03,
     'description_length': 0.05
}

def distance_score_calculator(score):
    if(score<1):
        return 1.1
    elif(score<5):
        return 1
    else:
        return 0.8

## Try with given distance scorer

In [11]:
shop_ranker = ShopRanker(shop, first_weight, distance_scorer=distance_score_calculator)
shop_ranker.get_top_rank(10, {"lat":13.755376,"lng":100.529406})

,name,description,lat,lng,distance,normalized_scores,weighted_scores
4677,Tanavakatsu,NaN,13.751749,100.536207,838.284636,8.184139,6.547311
48563,Hangar 220,NaN,13.751749,100.536207,838.284636,8.184139,6.547311
10814,ไส้กรอก ไส้อั่ว หมูล้วน ตลาดน้ำบางน้ำผึ้ง,NaN,13.755419,100.529401,4.824115,5.784139,5.784139
50308,Rosy-Cheeks,NaN,13.757801,100.536133,775.252185,7.015941,5.612753
47268,KOKO HUT (โกโก้ ฮัท พิซซ่า),NaN,13.757801,100.536133,775.252185,7.015941,5.612753
56651,The Duke's (เดอะ ดุ๊กส์) เมญ่า,NaN,13.754288,100.540273,1180.254019,6.797576,5.438061
51305,House Café x PASTRY ARCHITECT (เฮ้าส์คาเฟ่ x เ...,NaN,13.753284,100.539573,1122.785825,6.797576,5.438061
50950,Indigo Cafe & Restaurant (ร้าน อินดิโก้ คาเฟ่ ...,NaN,13.754288,100.540273,1180.254019,6.797576,5.438061
51078,Roadhouse Barbecue (โรดเฮ้าส์บาร์บีคิว),NaN,13.749247,100.527307,718.434840,6.797576,5.438061
22697,ฮ้านจาวเหนือ (Hanjaonua (north food)) ยูเนี่ยน...,NaN,13.749247,100.527307,718.434840,6.797576,5.438061

In [12]:
shop_ranker.get_top_rank(10, {"lat":172.819182,"lng":90.283171})

,name,description,lat,lng,distance,normalized_scores,weighted_scores
45026,Pizzaria - La Grotta,NaN,40.758791,-73.983382,4.047745e+06,4.863779,3.891023
53968,The Food Gallery,NaN,40.758791,-73.983382,4.047745e+06,4.863779,3.891023
39543,Ann Pho For Everyone Vietnamese Restaurant Cab...,NaN,38.782167,-77.182529,3.733059e+06,4.595608,3.676487
55702,Olive Restaurant,NaN,38.847422,-77.122693,3.741764e+06,4.595608,3.676487
53329,โรงแรมศรีพัฒนา (SRIPATTANA HOTEL),NaN,40.719799,-73.996221,4.043389e+06,4.563779,3.651023
58962,Thanken Wings (ธันเก้นวิงซ์),NaN,34.236664,-116.889676,4.100516e+06,4.340170,3.472136
58926,Bubba Gump,NaN,34.243390,-116.885406,4.100710e+06,4.340170,3.472136
59170,ร้านครัวอามี,NaN,34.243390,-116.885406,4.100710e+06,4.340170,3.472136
57165,McDonald's (แมคโดนัลด์) พหลโยธิน เพลส,NaN,40.779921,-73.980177,4.049962e+06,4.331976,3.465581
57910,house of prime rib,NaN,40.841583,-73.974763,4.056282e+06,4.331976,3.465581

In [13]:
## Try another logic for distance scorer

In [14]:
def distance_score_calculator(score):
    if(score<1):
        return 10000
    elif(score<5):
        return 1000
    else:
        return 100
    
    
shop_ranker = ShopRanker(shop, first_weight, distance_scorer=distance_score_calculator)
shop_ranker.get_top_rank(10, {"lat":13.755376,"lng":100.529406})

,name,description,lat,lng,distance,normalized_scores,weighted_scores
10814,ไส้กรอก ไส้อั่ว หมูล้วน ตลาดน้ำบางน้ำผึ้ง,NaN,13.755419,100.529401,4.824115,5.784139,5784.138536
4677,Tanavakatsu,NaN,13.751749,100.536207,838.284636,8.184139,818.413854
48563,Hangar 220,NaN,13.751749,100.536207,838.284636,8.184139,818.413854
50308,Rosy-Cheeks,NaN,13.757801,100.536133,775.252185,7.015941,701.594066
47268,KOKO HUT (โกโก้ ฮัท พิซซ่า),NaN,13.757801,100.536133,775.252185,7.015941,701.594066
56651,The Duke's (เดอะ ดุ๊กส์) เมญ่า,NaN,13.754288,100.540273,1180.254019,6.797576,679.757579
51305,House Café x PASTRY ARCHITECT (เฮ้าส์คาเฟ่ x เ...,NaN,13.753284,100.539573,1122.785825,6.797576,679.757579
50950,Indigo Cafe & Restaurant (ร้าน อินดิโก้ คาเฟ่ ...,NaN,13.754288,100.540273,1180.254019,6.797576,679.757579
51078,Roadhouse Barbecue (โรดเฮ้าส์บาร์บีคิว),NaN,13.749247,100.527307,718.434840,6.797576,679.757579
22697,ฮ้านจาวเหนือ (Hanjaonua (north food)) ยูเนี่ยน...,NaN,13.749247,100.527307,718.434840,6.797576,679.757579